export const configs = {
  PORT: process.env.PORT,
  DB_URL: process.env.MONGODB_URI,
  APP_SECRET: process.env.APP_SECRET,
  PRODUCT_SERVICE: "product_service",
  ORDER_SERVICE: "order_service",
  NOTIFICATION_SERVICE: "notification_service",
  CLOUD_NAME: process.env.CLOUD_NAME,
  API_KEY: process.env.API_KEY,
  API_SECRET: process.env.API_SECRET,
  USER_EMAIL: process.env.USER_EMAIL,
  APP_PASSWORD: process.env.APP_PASSWORD,
  SENDER: process.env.SENDER,
  BASE_URL: process.env.BASE_URL,
  PAYSTACK_SECRET: process.env.PAYSTACK_SECRET,
  NODE_ENV: process.env.NODE_ENV,
  ADMIN_APP_SECRET: process.env.ADMIN_APP_SECRET,
  REFERRAL_BONUS: process.env.REFERRAL_BONUS,
  FRONTEND_URL: process.env.FRONTEND_URL,
};
